/**
 * English report translations
 */
const reportEn = {
  appTitle: 'Digital Personal Secretary',
  taskReport: 'Task Report',
  filteredTaskReport: 'Filtered Task Report',
  allTasksReport: 'All Tasks Report',
  completedTasksReport: 'Completed Tasks Report',
  pendingTasksReport: 'Pending Tasks Report',
  inProgressTasksReport: 'In Progress Tasks Report',
  overdueTasksReport: 'Overdue Tasks Report',
  followupsReport: 'Follow-ups Report',
  workLogsReport: 'Daily Work Log Report',
  generatedOn: 'Generated Date',
  filters: 'Filters',
  totalTasks: 'Total Tasks',
  totalFollowups: 'Total Follow-ups',
  totalWorkLogs: 'Total Activities',
  totalDuration: 'Total Duration',
  totalRecords: 'Total Records',
  generatedBy: 'Generated by Digital Personal Secretary',
  page: 'Page',
  noFilter: 'No filters applied',
  noDeadline: 'No deadline',
  noDate: 'No date',
  none: 'None',

  // Column Headers
  colPerson: 'Person',
  colSubject: 'Subject',
  colTitle: 'Title',
  colDescription: 'Description',
  colPriority: 'Priority',
  colStatus: 'Status',
  colDepartment: 'Department',
  colDependency: 'Dependency',
  colDeadline: 'Deadline',
  colNextFollowup: 'Next Follow-up',
  colCreatedAt: 'Created At',
  colDate: 'Date',
  colCategory: 'Category',
  colDuration: 'Duration',
  colProject: 'Project',
  colRelatedTask: 'Related Task',
  colRelatedFollowup: 'Related Follow-up',
  colNotes: 'Notes',

  // Summary labels for Follow-ups
  summaryTotal: 'Total Follow-ups',
  summaryPending: 'Pending',
  summaryWaitingReply: 'Waiting Reply',
  summaryCompleted: 'Completed',
  summaryOverdue: 'Overdue',
  summaryToday: 'Today',
  summaryTomorrow: 'Tomorrow',

  // UI Priority Labels
  priorityHigh: 'High',
  priorityMedium: 'Medium',
  priorityLow: 'Low',

  // UI Status Labels
  statusPending: 'Pending',
  statusInProgress: 'In Progress',
  statusCompleted: 'Completed',
  statusWaitingReply: 'Waiting Reply',
  statusOverdue: 'Overdue',
};

export default reportEn;
